# 10 Numpy exercises

This [kaggle link](https://www.kaggle.com/utsav15/100-numpy-exercises) is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


> **_NOTE_** : Although most of them are quite easy and one-liner, don't burden or stress youself to solve all of them. It may seem overwhelming, hence I have hand-picked 10 questions for you to try hands on.

PS. Just kidding, no hand picking. Just ran
```
x = numpy.random.randint(100, size=(10))
>>> array([13, 25, 26, 29, 30, 60, 62, 73, 89, 90])
```
And voila, you have the questions.🙃

In [1]:
import numpy as np
import random

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [2]:
arr = np.random.randint(1, high=1000, size=100).reshape(10,10)

In [3]:
arr

array([[482, 315, 164, 717, 397, 533, 789, 853, 580, 348],
       [375, 906, 740, 206, 168, 454,  65, 688,  42, 871],
       [723, 888, 159, 995, 988, 918,  60,  32, 486, 478],
       [435,  99, 543, 624, 759, 661, 928, 713, 746, 514],
       [467, 112,  21, 457, 123, 152, 536, 872, 693, 865],
       [882, 290, 678, 937, 345, 760,  54, 578, 296, 712],
       [423, 559, 429, 111,  96, 618, 617, 945, 475,  88],
       [460, 961, 226, 613, 445, 512, 173, 954, 708, 911],
       [480, 248, 708, 663, 864, 309, 516, 611, 792, 989],
       [931, 413, 812, 920, 764, 116, 661, 192, 279,   7]])

In [4]:
maxi = arr[0][0]
mini = arr[0][0]
for i in range(10):
    for j in range(10):
        if arr[i][j] > maxi:
            maxi = arr[i][j]
        if arr[i][j] < mini:
            mini = arr[i][j] 

In [5]:
print(maxi, mini)

995 7


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [6]:
arr2 = np.random.randint(1, high=1000, size=100)

In [7]:
arr2

array([439, 900, 981, 205, 861, 262, 630, 466, 513, 744, 477, 453, 942,
       585, 817, 699,  17, 660, 105, 871, 252, 105, 678,  36, 487, 467,
       623, 438,  59,  77, 578, 446,  83, 352, 322, 460, 233, 387, 881,
       204, 749, 723, 634,   3, 859, 823, 737, 767, 759, 646, 156, 400,
       113, 733, 811, 277, 697, 749,  51, 669, 323, 422, 826, 433, 415,
       318, 527, 244, 975, 957, 174,  17,  19, 827, 258,  95,  90, 205,
       310,  44, 647, 409, 439, 152, 903,  17, 779, 788, 546, 268, 286,
       328, 494, 972, 765,  77, 983, 475, 971, 191])

In [8]:
for i,n in enumerate(arr2):
    if n>3 and n<8:
        arr2[i] = -arr2[i]
arr2

array([439, 900, 981, 205, 861, 262, 630, 466, 513, 744, 477, 453, 942,
       585, 817, 699,  17, 660, 105, 871, 252, 105, 678,  36, 487, 467,
       623, 438,  59,  77, 578, 446,  83, 352, 322, 460, 233, 387, 881,
       204, 749, 723, 634,   3, 859, 823, 737, 767, 759, 646, 156, 400,
       113, 733, 811, 277, 697, 749,  51, 669, 323, 422, 826, 433, 415,
       318, 527, 244, 975, 957, 174,  17,  19, 827, 258,  95,  90, 205,
       310,  44, 647, 409, 439, 152, 903,  17, 779, 788, 546, 268, 286,
       328, 494, 972, 765,  77, 983, 475, 971, 191])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [9]:
sum(range(5), -1)

9

#### 30. How to find common values between two arrays? (★☆☆)

In [10]:
arr3 = np.random.randint(1, high=1000, size=100)
arr4 = np.random.randint(1, high=1000, size=100)
print(arr3,"\n",arr4)

[414 685 788 429  37 682 549 500   8 824 463 647 180 573 898  65 645 699
 937 300 163 417 886 873 647 738 382 464  48 885  49 206 376 978  63  56
  28 934 896 646 574 958 656  30 387 754 875 936 454 863 973 509  88  56
 666 708 225 552 354 597 190 779 409 529 971 497 202 761 878 282 490 678
 418 485 127 856  99 382  77 836 914  78 828 675  43 942 412 189 993 574
 202 483 662 344 918 378 383 341  40 852] 
 [517 456 836 631 624  49 639 188 617 162 529 461 678 363 743 721 299 918
 123 848 371 971 990 299 295 929 109 648 296 550 429 415 421 973 614 746
 290 854 939 844  49 655 704 132 997 465  86 724 510 297 213 115 426 203
 313 678 186 941 215 159 225 453 568 423  60 428 456 458  71  37  55 702
 365 731  72 929 707  17 756 128 404 972 816 978 532 602  57 290 855 888
 533 405 732 101 356 297 844 881 780 368]


In [11]:
arr3_set = set(arr3)
arr4_set = set(arr4)
print(arr3_set & arr4_set)

{225, 836, 37, 678, 971, 429, 973, 529, 49, 978, 918}


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [12]:
arr4 = np.random.randint(0, high=2, size=100).reshape(5,20)
arr4

array([[0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0],
       [1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1],
       [0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1],
       [1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1]])

In [13]:
(row, col) = arr4.shape

In [14]:
count = 0
for i in range(col):
    for j in range(row):
        if arr4[j][i]==0:
            count+=1
    if count == row:
        print(i)
    count=0

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [15]:
arr5 = np.random.randint(1, 100, (1,3))
arr6 = np.random.randint(1, 100, (3,1))

In [16]:
print(arr5, "\n\n", arr6)

[[94 41 62]] 

 [[92]
 [12]
 [74]]


In [17]:
# how do you add 2 distinctly sized arrays?! like mendel's matching boxes xD
arr7 = np.zeros((3,3))
for i in range(3):
    arr7[0][i]+=arr6[i]
    arr7[i][0]+=arr5[0][i]
arr7 = arr7.T

In [18]:
row, col = arr7.shape

In [19]:
for i in range(1, row):
    for j in range(1, col):
        arr7[i][j]= arr7[i][0] + arr7[0][j]
arr7

array([[186.,  41.,  62.],
       [ 12.,  53.,  74.],
       [ 74., 115., 136.]])

In [20]:
# Solution
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [21]:
arr8 = np.random.randint(1,100,(10,3))
arr8

array([[13, 64, 82],
       [84, 76,  6],
       [ 7, 50, 54],
       [ 2, 95, 88],
       [98, 42, 24],
       [58, 78, 60],
       [ 9, 29, 57],
       [43,  6, 69],
       [77, 22, 74],
       [91, 46, 25]])

In [22]:
# didn't understand the meaning of composing

#### 89. How to get the n largest values of an array (★★★)

In [23]:
arr9 = np.random.randint(1, 100, 1000)
arr9

array([85,  4, 91, 46, 86, 51, 74, 33, 14, 77, 45, 53, 93, 37, 52, 56, 83,
       66, 75, 88, 34, 47, 98, 87,  9, 28, 78, 97, 12, 73, 79, 48, 88, 58,
       45, 84, 25, 54, 64, 58, 56, 23, 85, 87, 76, 99, 55, 39, 77, 24,  5,
       83, 68, 25, 33, 39, 74,  5, 78,  5, 98,  9, 81, 65, 50,  9, 72, 13,
       64, 85, 49, 70, 47, 30, 43, 67,  9, 68, 65, 83, 94, 29, 64, 80, 68,
       85, 36, 41, 84, 27, 46, 15, 53, 36,  4, 31, 15, 80, 39, 66, 72, 74,
       97, 69,  8, 90, 75, 11, 80,  8, 99, 96, 73, 66, 72, 51, 51, 42, 91,
        5, 51, 18, 29, 37, 24, 94, 18, 23, 91, 95, 35, 11, 10, 88, 11,  3,
       48, 74, 16, 79, 41, 54, 11, 82, 14, 94, 92, 62,  2, 10,  1, 62, 13,
       35, 30, 96, 29, 16, 82, 15, 32, 54, 90, 70, 82, 41, 64, 52, 67, 81,
       51, 58,  9, 89, 77, 69, 62, 58, 81, 30, 28, 83, 90, 25, 42, 27, 28,
       50, 40, 17, 90, 39, 95, 95, 89, 79,  6, 90, 45, 34, 22, 10, 49, 80,
       23, 36, 74, 93, 55, 29, 92,  3, 11, 87, 71, 13, 62, 94, 12, 82,  8,
        4,  1, 46, 53, 80

In [24]:
arr9.sort()
arr9

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,
        2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,
        4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
        8,  8,  8,  8,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
        9,  9,  9,  9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11,
       11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12,
       13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14, 14, 14,
       14, 14, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16,
       16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 17,
       17, 17, 17, 17, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 19, 19, 19,
       19, 19, 19, 19, 19, 20, 20, 20, 20, 21, 21, 21, 21, 21, 21, 21, 21,
       22, 22, 22, 22, 22

In [25]:
n = 2
arr9[-n:]

array([99, 99])

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [26]:
vecNumber = 5
dim = 4
arr10 = np.random.random((vecNumber, dim))*10
# vectors in each row

In [27]:
arr10

array([[3.23674833, 6.61846755, 6.24314777, 7.49927481],
       [5.87195013, 0.3839236 , 0.3243313 , 5.16477065],
       [7.68082593, 5.16186552, 0.74785166, 7.16048516],
       [3.80958366, 5.94903075, 0.50269832, 3.48526883],
       [9.91102538, 3.66696372, 1.66584613, 1.31917892]])

In [28]:
for i in range(vecNumber):
    for j in range(vecNumber):
        dot = sum(arr10[i]*arr10[j])
        print("vec{} with vec{} yields {}".format(i, j, dot))

vec0 with vec0 yields 149.4966692878018
vec0 with vec1 yields 62.303893328461086
vec0 with vec2 yields 117.39193436354927
vec0 with vec3 yields 80.97953922376209
vec0 with vec4 yields 76.64218393141117
vec1 with vec0 yields 62.303893328461086
vec1 with vec1 yields 61.407242326741454
vec1 with vec2 yields 84.30800409880202
vec1 with vec3 yields 42.817313521546794
vec1 with vec4 yields 66.95842325010193
vec2 with vec0 yields 117.39193436354927
vec2 with vec1 yields 84.30800409880202
vec2 with vec2 yields 137.47177243498516
vec2 with vec3 yields 85.30100519473822
vec2 with vec4 yields 105.74500112734218
vec3 with vec0 yields 80.97953922376209
vec3 with vec1 yields 42.817313521546794
vec3 with vec2 yields 85.30100519473822
vec3 with vec3 yields 62.30369900410358
vec3 with vec4 yields 65.00687147811401
vec4 with vec0 yields 76.64218393141117
vec4 with vec1 yields 66.95842325010193
vec4 with vec2 yields 105.74500112734218
vec4 with vec3 yields 65.00687147811401
vec4 with vec4 yields 116.1903

These are some common np functions.
np.linspace
np.arange
np.loadtxt
np.random